<?php
	$title = 'Eliminar Usuario';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?> </h1>

<?php
	$url = $this->url('crud', ['action' => 'delete', 'id' => $id]);
?>


<form action="<?php echo $url ?>" method="POST">
	<p>¿Esta seguro de eliminar?</p>
	<div class="form-group">
		 <input  type="hidden" name="id" value="<?php $post->getId();?>">
		<input  type="submit" name="delete" value="Yes" class="btn btn-danger">
		<input  type="submit" name="delete" value="No" class="btn btn-default">
	</div>
</form>